language: cpp
git:
  submodules: false

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get install software-properties-common
  - sudo add-apt-repository ppa:george-edison55/cmake-3.x -y
  - sudo apt-get update -qq
  - sudo apt-get upgrade

before_script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release

script: make && make test

after_failure: if [ -d Testing ]; then cat Testing/Temporary/LastTest.log; fi