language: cpp
git:
  submodules: false

compiler:
  - gcc
  - clang

before_script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release

script: make && make test

after_failure: if [ -d Testing ]; then cat Testing/Temporary/LastTest.log; fi