language: cpp
git:
  submodules: false

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data

before_script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release

script: make && make test

after_failure: if [ -d Testing ]; then cat Testing/Temporary/LastTest.log; fi